import type { Asset } from "./types";

export const DEMO_ASSETS: Asset[] = [
  {
    id: "demo-01",
    name: "Summer serum — kitchen UGC",
    creator: "@maya.makes",
    platforms: ["meta", "tiktok"],
    usage: ["paid", "organic"],
    startsAt: "2026-06-01",
    endsAt: "2026-12-31",
    exclusive: false,
    contractUrl: "https://drive.example/contracts/maya-serum.pdf",
    notes: "Paid usage on Meta + TikTok. Organic reuse OK.",
    createdAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "demo-02",
    name: "Founder talking-head — Q3 offer",
    creator: "In-house studio",
    platforms: ["youtube", "web"],
    usage: ["organic", "paid"],
    startsAt: "2026-07-15",
    endsAt: "2026-10-02",
    exclusive: false,
    contractUrl: "",
    notes: "Talent release on file. Refresh CTA before expiry.",
    createdAt: "2026-07-15T12:00:00.000Z",
  },
  {
    id: "demo-03",
    name: "TikTok Shop stitch pack",
    creator: "@leo.cuts",
    platforms: ["tiktok"],
    usage: ["paid", "whitelisting"],
    startsAt: "2026-08-01",
    endsAt: "2026-10-05",
    exclusive: true,
    contractUrl: "https://drive.example/contracts/leo-exclusive.pdf",
    notes: "Exclusive 60-day Spark Ads whitelist. Do not run after Oct 5.",
    createdAt: "2026-08-01T10:30:00.000Z",
  },
  {
    id: "demo-04",
    name: "Telegram channel unboxing",
    creator: "@kat.unbox",
    platforms: ["telegram", "web"],
    usage: ["organic"],
    startsAt: "2026-04-01",
    endsAt: "2026-09-01",
    exclusive: false,
    contractUrl: "",
    notes: "Organic only. Paid boost was never licensed.",
    createdAt: "2026-04-02T08:00:00.000Z",
  },
  {
    id: "demo-05",
    name: "Meta Advantage+ stills set",
    creator: "Northside Agency",
    platforms: ["meta"],
    usage: ["paid"],
    startsAt: "2026-01-10",
    endsAt: "2026-08-15",
    exclusive: false,
    contractUrl: "https://drive.example/contracts/northside-stills.pdf",
    notes: "Campaign already off. Keep for audit trail.",
    createdAt: "2026-01-10T11:00:00.000Z",
  },
  {
    id: "demo-06",
    name: "YouTube pre-roll — winter drop",
    creator: "@aria.lens",
    platforms: ["youtube", "meta"],
    usage: ["paid", "whitelisting"],
    startsAt: "2026-09-01",
    endsAt: "2027-02-28",
    exclusive: true,
    contractUrl: "https://drive.example/contracts/aria-winter.pdf",
    notes: "Brand-safe until Feb 2027. No competitor category ads.",
    createdAt: "2026-09-01T16:20:00.000Z",
  },
];
